// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

//Sistema de número de versão: major.minor.build.revision
// major: Mudanças grandes no sistema
// minor: Novos recursos/funcionalidades
// build: Ano e mês
// revision: Dia e minutos (a partir de meia-noite) dividido por 15
[assembly: AssemblyVersion("1.0.1504.2062")]
[assembly: AssemblyFileVersion("1.0.1504.2062")]
